# To execute this docker-compose yml file use `docker-compose -f <file_name> up`
# or be in same directory as docker-compose.yml (default runs the same filename)
#
# Run both containers independently w/o docker-compose:
# docker run -d -p 0.0.0.0:4444:4444 -p 0.0.0.0:5900:5900 -v /dev/shm:/dev/shm --name selenium selenium/standalone-chrome-debug:latest
# docker run -p 0.0.0.0:8675:8675 -it --entrypoint zsh --link selenium:selenium -v $(pwd):/pytest_framework pytest_framework:latest
# docker run -it --entrypoint zsh pytest_framework:latest
#
# run with docker-compose:
# Start services detached (in background):
#   docker-compose up -d
# Run pytest_framework container in interactive mode:
#   docker-compose exec pytest_framework zsh


# # https://github.com/SeleniumHQ/docker-selenium/wiki/Getting-Started-with-Docker-Compose

version: "3"

services:
  chrome:
    image: selenium/node-chrome:4.24.0-20240830
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - custom_network

  # edge:
  #   image: selenium/node-edge:4.24.0-20240830
  #   shm_size: 2gb
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     - SE_EVENT_BUS_HOST=selenium-hub
  #     - SE_EVENT_BUS_PUBLISH_PORT=4442
  #     - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  #   networks:
  #     - custom_network

  firefox:
    image: selenium/node-firefox:4.24.0-20240830
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - custom_network

  selenium-hub:
    image: selenium/hub:4.24.0-20240830
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - custom_network

  pytest_framework:
    image: pytest-framework:latest
    container_name: pytest_framework
    depends_on:
      - selenium-hub
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "8675:8675"
    volumes:
      - ./:/pytest_framework
    networks:
      - custom_network
    environment:
        - TZ=America/New_York

networks:
  custom_network:
    driver: "bridge"

